### ISSUE TITLE
Errors on every page load

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#53]
Currently I get the following error on the console running the application on every single page load. That doesn't seem right^^

```
Error
    at module.fallback (/home/kara/develop/kolledata/controllers/error.js:9:19)
    at callbacks (/home/kara/develop/kolledata/node_modules/express/lib/router/index.js:164:37)
    at param (/home/kara/develop/kolledata/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/kara/develop/kolledata/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/kara/develop/kolledata/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/kara/develop/kolledata/node_modules/express/lib/router/index.js:33:10)
    at next (/home/kara/develop/kolledata/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.json [as handle] (/home/kara/develop/kolledata/node_modules/express/node_modules/connect/lib/middleware/json.js:42:37)
    at next (/home/kara/develop/kolledata/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.urlencoded [as handle] (/home/kara/develop/kolledata/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:40:37)
```

**Comment by preip** [comment]
Solved
